version: '3.8'
services:
  frontend-test:
    build:
      context: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - test
  backend-test:
    build:
      context: backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    networks:
      - test
  nginx-test:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - test
volumes:
  test:
networks:
  test: