version: '3.8'
services:
  frontend-test:
    build:
      context: frontend
    ports:
      - "3000:80"
    volumes:
      - .:/app
    networks:
      - test
  backend-test:
    build:
      context: backend
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - test
volumes:
  test:
networks:
  test: